// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjDV3LSWeBXjrmKTJJqXCYoaAmPJBG_e0',
    appId: '1:1059736049901:web:558d0a49e0eb5d0678d4e4',
    messagingSenderId: '1059736049901',
    projectId: 'ecoplant-81ab5',
    authDomain: 'ecoplant-81ab5.firebaseapp.com',
    storageBucket: 'ecoplant-81ab5.firebasestorage.app',
    measurementId: 'G-ZK2V183S59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiC62Pd2rFAUB1ITLO93ZHNhZl7gQvr2I',
    appId: '1:1059736049901:android:cb93e60e7315adb178d4e4',
    messagingSenderId: '1059736049901',
    projectId: 'ecoplant-81ab5',
    storageBucket: 'ecoplant-81ab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7jnG4tGkleYhSFybnukW6BGhRtLKsUA',
    appId: '1:1059736049901:ios:b2333717257deede78d4e4',
    messagingSenderId: '1059736049901',
    projectId: 'ecoplant-81ab5',
    storageBucket: 'ecoplant-81ab5.firebasestorage.app',
    iosBundleId: 'com.example.ecoplant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq7jnG4tGkleYhSFybnukW6BGhRtLKsUA',
    appId: '1:1059736049901:ios:b2333717257deede78d4e4',
    messagingSenderId: '1059736049901',
    projectId: 'ecoplant-81ab5',
    storageBucket: 'ecoplant-81ab5.firebasestorage.app',
    iosBundleId: 'com.example.ecoplant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjDV3LSWeBXjrmKTJJqXCYoaAmPJBG_e0',
    appId: '1:1059736049901:web:2f6e138212a0436878d4e4',
    messagingSenderId: '1059736049901',
    projectId: 'ecoplant-81ab5',
    authDomain: 'ecoplant-81ab5.firebaseapp.com',
    storageBucket: 'ecoplant-81ab5.firebasestorage.app',
    measurementId: 'G-YGKJZQPY1M',
  );
}
